### ISSUE TITLE
Problem displaying GitXiv pages on Chrome browser

### ISSUE THREAD

**Issue by cwreynolds** [samim23/GitXiv#50] opened 2016-06-13 03:51 UTC
Since June 2, GitXiv has not been working for me. Today I realized that it was not working for me _on Chrome_: using **Google Chrome Version 51.0.2704.79 (64-bit)** on **OS X 10.10.5**.  Here is http://gitxiv.com/posts/6YznFwcBAmNMwscuQ/forest-floor-visualizations-of-random-forests on Chrome:

<img width="1331" alt="screen shot 2016-06-12 at 8 46 33 pm" src="https://cloud.githubusercontent.com/assets/1909341/15996643/ee974efc-30de-11e6-8d6c-e00db6fe0fb2.png">

and on Safari (Version 9.1.1 (10601.6.17)):

<img width="1381" alt="screen shot 2016-06-12 at 8 46 50 pm" src="https://cloud.githubusercontent.com/assets/1909341/15996648/02f0518c-30df-11e6-980c-8fa3b4bf4e7c.png">

**Comment by ekshaks** [comment] 2016-06-14 07:32
I think there is a problem with one of the iron router's components.
Fix suggested here https://forums.meteor.com/t/solved-error-handler-with-name-u-already-exists/23910/20
meteor update iron:middleware-stack

**Comment by samim23** [comment] 2016-06-14 08:43
Thanks for the info! We will be porting GitXiv over to a new version of the backend shortly.

**Comment by ynyounuo** [comment] 2016-06-15 11:07
duplicate of #49

**Comment by petro-rudenko** [comment] 2016-06-27 10:22
Having the same issue. Chome  51.0.2704.103 (64-bit) on OS X. Here's a traceback from dev tools:
```
Exception in callback of async function: Error: Handler with name 'u' already exists.
    at i._create (http://gitxiv.com/5ecf7218c3efc86b779e2c62a443fed07f4fd970.js:153:1577)
    at i.push (http://gitxiv.com/5ecf7218c3efc86b779e2c62a443fed07f4fd970.js:153:1761)
    at http://gitxiv.com/5ecf7218c3efc86b779e2c62a443fed07f4fd970.js:153:2011
    at Array.forEach (native)
    at Function.A.each.A.forEach (http://gitxiv.com/5ecf7218c3efc86b779e2c62a443fed07f4fd970.js:1:865)
    at i.append (http://gitxiv.com/5ecf7218c3efc86b779e2c62a443fed07f4fd970.js:153:1941)
    at http://gitxiv.com/5ecf7218c3efc86b779e2c62a443fed07f4fd970.js:153:2130
    at Array.forEach (native)
    at Function.A.each.A.forEach (http://gitxiv.com/5ecf7218c3efc86b779e2c62a443fed07f4fd970.js:1:865)
    at i.append (http://gitxiv.com/5ecf7218c3efc86b779e2c62a443fed07f4fd970.js:153:1941)```

**Comment by soupault** [comment] 2016-06-27 19:31
Same here. Doesn't show the body in Chrome/Chromium, but works fine in Firefox-based browsers.

**Comment by renjiushuihan** [comment] 2016-06-29 12:24
Same here.

**Comment by ArunAniyan** [comment] 2016-07-04 09:14
In my case does not load in Chrome , but opens in firefox. Running on Ubuntu 16.04

**Comment by Zugunruhekami** [comment] 2016-07-05 01:52
is this problem fixed? i can access the site via Microsoft Edge but not with Chrome.

**Comment by sheerun** [comment] 2016-07-11 09:24
Same

**Comment by steven2358** [comment] 2016-07-12 09:36
Same

**Comment by johann-petrak** [comment] 2016-07-14 11:49
Unusable with Chrome 51.0.2704.106 (64-bit) on Ubuntu.

**Comment by samim23** [comment] 2016-07-25 10:43
Hey everybody. Ported GitXiv to a new version of Meteor and a new Server/Host. Should all work nicely again on Chrome as well. Thanks for the patience and sorry for the inconvenience!

**Closed** 2016-07-25 10:44 UTC
